services:
  ctrlpagos_app_v1:
    build: ctrl-ingresos-back-v1
    mem_limit: 512m
    ports:
      - "8011:8011"
    environment:
      DB_URL: jdbc:mysql://ctrl_pagos_db_2:3306/rest_api_ctrlpagos_db_2?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: ArMxfigpab024$$
    restart: always
    depends_on:
      ctrl_pagos_db_2:
        condition: service_healthy
  ctrl_pagos_db_2:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ArMxfigpab024$$
      MYSQL_PASSWORD: ArMxfigpab024$$
      MYSQL_DATABASE: rest_api_ctrlpagos_db_2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - my-db-2:/var/lib/mysql
  ctrl_pagos_app_front_v1:
    build: ctrl-ingresos-front-v1
    ports:
      - "4201:4201"
    depends_on:
      - ctrlpagos_app_v1
volumes:
  my-db-2:  
    
    